# Generated by Django 5.2.17 on 2026-09-20 05:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0006_alter_artwork_order'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='artwork',
            options={'ordering': ['-order']},
        ),
        migrations.AlterModelOptions(
            name='bio',
            options={'verbose_name': 'information page', 'verbose_name_plural': 'information page'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order', 'name'], 'verbose_name_plural': 'categories'},
        ),
        migrations.AddField(
            model_name='artwork',
            name='dimensions',
            field=models.CharField(blank=True, help_text='e.g. 13" x 16"', max_length=100),
        ),
        migrations.AddField(
            model_name='artwork',
            name='height',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='artwork',
            name='image_display',
            field=models.ImageField(blank=True, editable=False, upload_to='artworks/display/'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='image_thumb',
            field=models.ImageField(blank=True, editable=False, upload_to='artworks/thumb/'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='medium',
            field=models.CharField(blank=True, help_text='e.g. ink, pigment, oil on cardboard', max_length=200),
        ),
        migrations.AddField(
            model_name='artwork',
            name='price',
            field=models.CharField(blank=True, help_text='e.g. $750, sold, NFS', max_length=100),
        ),
        migrations.AddField(
            model_name='artwork',
            name='wall_left',
            field=models.DecimalField(decimal_places=2, default=32, help_text='Left edge, as % of the wall photo width.', max_digits=5),
        ),
        migrations.AddField(
            model_name='artwork',
            name='wall_top',
            field=models.DecimalField(decimal_places=2, default=26.67, help_text='Top edge, as % of the wall photo height.', max_digits=5),
        ),
        migrations.AddField(
            model_name='artwork',
            name='wall_view',
            field=models.CharField(blank=True, choices=[('', "Don't offer"), ('small', 'Close-up wall (smaller works)'), ('large', 'Wide room (larger works)')], default='', max_length=5, verbose_name='"View on wall"'),
        ),
        migrations.AddField(
            model_name='artwork',
            name='wall_width',
            field=models.DecimalField(decimal_places=2, default=24, help_text='Width of the work, as % of the wall photo width.', max_digits=5),
        ),
        migrations.AddField(
            model_name='artwork',
            name='width',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='bio',
            name='biography_banner',
            field=models.ImageField(blank=True, upload_to='information/'),
        ),
        migrations.AddField(
            model_name='bio',
            name='biography_image',
            field=models.ImageField(blank=True, upload_to='information/'),
        ),
        migrations.AddField(
            model_name='bio',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='bio',
            name='exhibitions',
            field=models.TextField(blank=True, help_text='One per line.'),
        ),
        migrations.AddField(
            model_name='bio',
            name='instagram',
            field=models.CharField(blank=True, help_text='Handle only, without the @', max_length=100),
        ),
        migrations.AddField(
            model_name='bio',
            name='statement',
            field=models.TextField(blank=True, verbose_name="artist's statement"),
        ),
        migrations.AddField(
            model_name='bio',
            name='statement_banner',
            field=models.ImageField(blank=True, upload_to='information/'),
        ),
        migrations.AddField(
            model_name='bio',
            name='statement_image',
            field=models.ImageField(blank=True, upload_to='information/'),
        ),
        migrations.AddField(
            model_name='category',
            name='layout',
            field=models.CharField(choices=[('tiles', 'Square tiles, 3 columns'), ('masonry', 'Uncropped, 2 columns')], default='tiles', max_length=10),
        ),
        migrations.AddField(
            model_name='category',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.AddField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, help_text='Leave empty for a top-level section shown in the main menu.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='artworks.category'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artworks', to='artworks.category'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=models.ImageField(height_field='height', upload_to='artworks/', width_field='width'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='is_featured',
            field=models.BooleanField(default=False, help_text='Show in the home page slideshow.'),
        ),
        migrations.AlterField(
            model_name='artwork',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='bio',
            name='content',
            field=models.TextField(verbose_name='biography'),
        ),
        migrations.CreateModel(
            name='SeriesTile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='tiles/')),
                ('image_thumb', models.ImageField(blank=True, editable=False, upload_to='tiles/thumb/')),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
                ('category', models.ForeignKey(limit_choices_to={'parent__isnull': False}, on_delete=django.db.models.deletion.CASCADE, related_name='tiles', to='artworks.category')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
