# Generated by Django 5.2.17 on 2026-09-20 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artworks', '0007_joseph_site_structure'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='wall_view',
            field=models.CharField(blank=True, choices=[('', "Don't offer"), ('small', 'Close-up wall (smaller works)'), ('large', 'Wide room (larger works)')], default='large', max_length=5, verbose_name='"View on wall"'),
        ),
    ]
